# ============================================================================
#  TrueGaze - Install One-Click Launchers
#
#  Creates Windows shortcuts so the whole build/deploy/verify/launch cycle is a
#  double-click. Also places a .cmd shim in the project root for use from any
#  shell that is not PowerShell.
#
#  Run once:
#      .\scripts\Install-OneClick.ps1
# ============================================================================

[CmdletBinding()]
param(
    [string]$GamePath,
    # Create the shortcut on the Desktop as well as in the project folder.
    [switch]$Desktop = $true
)

$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path $PSScriptRoot -Parent
$deployScript = Join-Path $PSScriptRoot 'Deploy-TrueGaze.ps1'

if (-not (Test-Path $deployScript)) {
    throw "Deploy-TrueGaze.ps1 not found next to this script. Expected: $deployScript"
}

Write-Host ''
Write-Host 'TrueGaze - Installing one-click launchers' -ForegroundColor Cyan
Write-Host '===========================================' -ForegroundColor Cyan
Write-Host ''

# ---------------------------------------------------------------------------
# A .cmd shim in the project root.
#
# Shortcuts are convenient but shell-specific; a .cmd file works from Explorer,
# from a terminal, from a scheduled task, and from another script. It also
# survives being copied around, since it resolves its own location.
# ---------------------------------------------------------------------------
$cmdPath = Join-Path $projectRoot 'TrueGaze.cmd'
$cmdLines = @(
    '@echo off',
    'REM TrueGaze one-click launcher. Generated by scripts\Install-OneClick.ps1.',
    'REM Runs build -> deploy -> verify -> launch, and refuses to launch if the',
    'REM health check fails.',
    'setlocal',
    'set "HERE=%~dp0"',
    'if not defined VCPKG_ROOT set "VCPKG_ROOT=D:\vcpkg"',
    '',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%HERE%scripts\Deploy-TrueGaze.ps1" %*',
    '',
    'REM Capture the result immediately. Any subsequent successful command -',
    'REM including echo - resets ERRORLEVEL to 0, so reading it after the',
    'REM message below would always report success.',
    'set "TG_EXIT=%ERRORLEVEL%"',
    '',
    'if not "%TG_EXIT%"=="0" (',
    '    echo.',
    '    echo TrueGaze did not complete successfully ^(exit %TG_EXIT%^).',
    '    REM Pause only for a bare double-click, where the console window would',
    '    REM otherwise vanish before the message could be read. Any argument',
    '    REM means automation, which must never block.',
    '    if "%~1"=="" pause',
    ')',
    '',
    'endlocal & exit /b %TG_EXIT%'
)
Set-Content -Path $cmdPath -Value $cmdLines -Encoding ASCII
Write-Host ("  OK   Created shim: " + $cmdPath) -ForegroundColor Green

# ---------------------------------------------------------------------------
# Shortcuts.
# ---------------------------------------------------------------------------
function New-TGShortcut {
    param(
        [string]$Path,
        [string]$Target,
        [string]$Arguments,
        [string]$Description,
        [string]$WorkingDir
    )

    $shell = New-Object -ComObject WScript.Shell
    $sc = $shell.CreateShortcut($Path)
    $sc.TargetPath = $Target
    $sc.Arguments = $Arguments
    $sc.Description = $Description
    $sc.WorkingDirectory = $WorkingDir
    $sc.WindowStyle = 1
    # A terminal icon rather than the PowerShell logo: this is a build tool.
    $sc.IconLocation = "$env:SystemRoot\System32\shell32.dll,21"
    $sc.Save()
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($shell) | Out-Null
}

$psExe = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'

$shortcuts = @(
    @{
        Name   = 'TrueGaze - Build and Launch.lnk'
        Args   = "-NoProfile -ExecutionPolicy Bypass -File `"$deployScript`""
        Desc   = 'Build, deploy, verify and launch TrueGaze'
    },
    @{
        Name   = 'TrueGaze - Safe Load-Only Test.lnk'
        Args   = "-NoProfile -ExecutionPolicy Bypass -File `"$deployScript`" -LoadOnly"
        Desc   = 'Deploy with simulation disabled and launch, to prove the plugin loads safely'
    },
    @{
        Name   = 'TrueGaze - Verify Only.lnk'
        Args   = "-NoProfile -ExecutionPolicy Bypass -File `"$deployScript`" -NoLaunch"
        Desc   = 'Build, deploy and run the pre-flight health check without launching'
    },
    @{
        Name   = 'TrueGaze - Analyse Last Run.lnk'
        Args   = "-NoProfile -ExecutionPolicy Bypass -File `"$deployScript`" -PostRun"
        Desc   = 'Parse TrueGaze.log and report what happened on the last run'
    }
)

$made = @()
foreach ($s in $shortcuts) {
    $p = Join-Path $projectRoot $s.Name
    New-TGShortcut -Path $p -Target $psExe -Arguments $s.Args -Description $s.Desc -WorkingDir $projectRoot
    $made += $p
    Write-Host ("  OK   " + $s.Name) -ForegroundColor Green
}

if ($Desktop) {
    # Keep the Desktop uncluttered: one shortcut, not four.
    $desktopDir = [Environment]::GetFolderPath('Desktop')
    $dp = Join-Path $desktopDir 'TrueGaze Test.lnk'
    New-TGShortcut -Path $dp -Target $psExe `
        -Arguments "-NoProfile -ExecutionPolicy Bypass -File `"$deployScript`"" `
        -Description 'Build, deploy, verify and launch TrueGaze' `
        -WorkingDir $projectRoot
    Write-Host ("  OK   " + $dp) -ForegroundColor Green
}

Write-Host ''
Write-Host 'Done. Double-click "TrueGaze - Build and Launch" to run the full cycle.' -ForegroundColor Cyan
Write-Host ''
Write-Host 'Recommended order for a first test:' -ForegroundColor White
Write-Host '  1. TrueGaze - Verify Only          (fix anything it reports)' -ForegroundColor Gray
Write-Host '  2. TrueGaze - Safe Load-Only Test  (proves it loads without crashing)' -ForegroundColor Gray
Write-Host '  3. TrueGaze - Build and Launch     (the real test)' -ForegroundColor Gray
Write-Host '  4. TrueGaze - Analyse Last Run     (what actually happened)' -ForegroundColor Gray
Write-Host ''
